name: PlaceholderAddon
main: com.ericlam.mc.placeholder.addon.PapiAddon
version: ${project.version}
depend: [PlaceholderAPI, HyperNiteMC-Core]
api-version: "1.15"
author: Hydranapse_
commands:
  papi-addon:
    description: placeholder addon commands